[tasks.format-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build-grcov]
env = { CARGO_INCREMENTAL = "0", RUSTFLAGS = "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort", RUSTDOCFLAGS = "-Cpanic=abort" }
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.all]
dependencies = [
    "format-check",
    "build",
    "lint",
    "test"
]

[tasks.all-grcov]
dependencies = [
    "format-check",
    "build-grcov",
    "lint",
    "test"
]
