ldap_uri = ""
ldap_jit_search_base = "dc=example,dc=com"
ldap_jit_search_filter_str = "(&(objectClass=*))"
ldap_tls_reqcert = "always"
ldap_tls_cacert = ""
ldap_sasl_mech = "EXTERNAL"
ldap_default_bind_dn = ""
ldap_default_authtok = ""
ldap_tls_cert = ""
ldap_tls_key = ""
ldap_tls_key_standard = ""
ldap_jit_attr_name = "jitTriple"
ldap_host_attr_name = "userHostTuple"
jit_rule_not_found_prompt = "Couldn't find matching JIT rule. Did you request the access and was it approved?"
debug = true
